version: '3'
services:
  database:
    image: mongo:latest
    container_name: mongo
    # environment:       
    #   # - MONGO_INITDB_ROOT_USERNAME=admin
    #   # - MONGO_INITDB_ROOT_PASSWORD=admin
    #   # - MONGO_INITDB_DATABASE=imagica
    #   - MONGO_URL=mongodb://database/imagica
    volumes:
      - .mongo-volume:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017


  node:
    container_name: node
    build: myapp
    environment:
      - MONGO_URL=mongodb://database:27017/imagica
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
   
  angular:
    container_name: angular
    build: docker-mean
    ports:
      - 80:80
  
  


